import Head from 'next/head';
import Image from 'next/image';
import { home_data } from '../utils/data';

export default function Home({ data }: any) {
  const icon = data.front_end_skills_data[1].icon;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>TypeScript</h1>
        <Image
          src={icon}
          layout='fill'
          // style={{
          //   filter:
          //     'invert(44%) sepia(9%) saturate(5228%) hue-rotate(176deg) brightness(92%) contrast(83%)',
          // }}
          style={{ color: '#3178C6' }}
        />
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: {
      data: home_data,
    },
  };
};
